uselagoon/lagoon-images

images/php-fpm/7.2.Dockerfile
images/php-fpm/7.3.Dockerfile
images/php-fpm/7.4.Dockerfile

Duplicate of https://github.com/amazeeio/lagoon/pull/2209
Closes https://github.com/amazeeio/lagoon/issues/2207

Bump libcurl to the same version as curl - 7.69.1.

---

images/nginx/nginx.conf

Duplicate of https://github.com/amazeeio/lagoon/pull/2260
Closes https://github.com/amazeeio/lagoon/issues/2259

Use NGINX defined log_format main

---

helpers/update-versions.yml
images/php-cli-drupal/7.2.Dockerfile
images/php-cli-drupal/7.3.Dockerfile
images/php-cli-drupal/7.4.Dockerfile
images/php-cli/7.2.Dockerfile
images/php-cli/7.3.Dockerfile
images/php-cli/7.4.Dockerfile
images/php-fpm/7.2.Dockerfile
images/php-fpm/7.3.Dockerfile
images/php-fpm/7.4.Dockerfile

supersedes https://github.com/amazeeio/lagoon/pull/2314

Update version helper script and update Composer/Drush/New Relic

---

Jenkinsfile

This is currently bound to thethe ax51-1 node, as it is the only one with Node+Yarn on at the moment.

Add example building to Jenkinsfile

---

images/commons/fix-permissions

See https://github.com/amazeeio/lagoon/pull/2291 for details on this PR.

Improve the efficiency of fix-permissions

---

Jenkinsfile
Makefile

*TO-DO* - upload scan results to GitHub somehow?

re-enable trivy scanning of built images

---

images/commons/Dockerfile
images/mariadb/Dockerfile
images/nginx/Dockerfile
images/node-builder/12.Dockerfile
images/node-builder/14.Dockerfile
images/node/12.Dockerfile
images/node/14.Dockerfile
images/php-fpm/7.2.Dockerfile
images/php-fpm/7.3.Dockerfile
images/php-fpm/7.4.Dockerfile
images/postgres/11.Dockerfile
images/postgres/12.Dockerfile
images/python/3.7.Dockerfile
images/python/3.8.Dockerfile
images/redis/5.Dockerfile

Status of images in this PR
```
lagoon/commons (alpine 3.12.1)
lagoon/elasticsearch-6 (centos 7.6.1810)
lagoon/elasticsearch-7 (centos 7.7.1908)
lagoon/kibana-6 (centos 7.6.1810)
lagoon/kibana-7 (centos 7.7.1908)
lagoon/logstash-6 (centos 7.6.1810)
lagoon/logstash-7 (centos 7.6.1810)
lagoon/mariadb (alpine 3.12.1)
lagoon/mariadb-drupal (alpine 3.12.1)
lagoon/mongo (alpine 3.8.5)
lagoon/nginx (alpine 3.12.0)
lagoon/nginx-drupal (alpine 3.12.0)
lagoon/node-10 (alpine 3.11.6)
lagoon/node-10-builder (alpine 3.11.6)
lagoon/node-12 (alpine 3.12.1)
lagoon/node-12-builder (alpine 3.12.1)
lagoon/node-14 (alpine 3.12.1)
lagoon/node-14-builder (alpine 3.12.1)
lagoon/php-7.2-cli (alpine 3.12.1)
lagoon/php-7.2-cli-drupal (alpine 3.12.1)
lagoon/php-7.2-fpm (alpine 3.12.1)
lagoon/php-7.3-cli (alpine …
```

Update Alpine 3.11-based images to 3.12

---

images/varnish-drupal/drupal.vcl

Cleanup X-LAGOON Variable in Varnish to streamline this across lagoon containers

Cleanup X-LAGOON Header for Varnish

---

images/commons/lagoon/cronjob.sh

Issue 64/add call to sh for cronjobs

---

helpers/update-versions.yml
images/php-cli-drupal/7.2.Dockerfile
images/php-cli-drupal/7.3.Dockerfile
images/php-cli-drupal/7.4.Dockerfile
images/php-cli-drupal/8.0.Dockerfile
images/php-cli/7.2.Dockerfile
images/php-cli/7.3.Dockerfile
images/php-cli/7.4.Dockerfile
images/php-cli/8.0.Dockerfile
images/php-fpm/7.2.Dockerfile
images/php-fpm/7.3.Dockerfile
images/php-fpm/7.4.Dockerfile
images/php-fpm/8.0.Dockerfile

Update NewRelic to 9.16.0.295
Update Composer to 1.10.20
Update Drupal Console Launcher to 1.9.7
Update Drush Version to 8.4.6
Update Drush Launcher to 0.9.0

Componentes Update 2021-02 Edition

---

images/nginx/nginx.conf

Add map hash configuration.

---

images/commons/Dockerfile
images/elasticsearch/6.Dockerfile
images/elasticsearch/7.Dockerfile
images/kibana/6.Dockerfile
images/kibana/7.Dockerfile
images/logstash/6.Dockerfile
images/logstash/7.Dockerfile
images/mariadb/Dockerfile
images/nginx/Dockerfile
images/node/10.Dockerfile
images/node/12.Dockerfile
images/node/14.Dockerfile
images/php-fpm/7.2.Dockerfile
images/php-fpm/7.3.Dockerfile
images/php-fpm/7.4.Dockerfile
images/php-fpm/8.0.Dockerfile
images/postgres/11.Dockerfile
images/postgres/12.Dockerfile
images/python/2.7.Dockerfile
images/python/3.7.Dockerfile
images/python/3.8.Dockerfile
images/redis/5.Dockerfile
images/redis/6.Dockerfile

These are just some minor patches I made to the images while working on them recently.

Use fix-permissions for /etc/passwd instead of chmod g+w

---

helpers/update-versions.yml
images/php-cli-drupal/7.2.Dockerfile
images/php-cli-drupal/7.3.Dockerfile
images/php-cli-drupal/7.4.Dockerfile
images/php-cli-drupal/8.0.Dockerfile
images/php-cli/7.2.Dockerfile
images/php-cli/7.3.Dockerfile
images/php-cli/7.4.Dockerfile
images/php-fpm/7.2.Dockerfile
images/php-fpm/7.3.Dockerfile
images/php-fpm/7.4.Dockerfile
images/php-fpm/8.0.Dockerfile

Update New Relic agent to support PHP8. Also bump drush and composer (patch release)

---

images/php-fpm/8.0.Dockerfile

Fix PHP Yaml warning

---

images/mariadb/10.4.Dockerfile
images/mariadb/10.5.Dockerfile

http://mysqltuner.pl DNS does not resolve currently, and may have expired

use github for mysqltuner

---

images/toolbox/Dockerfile
images/toolbox/README.md

This PR adds mongodb-tools to the toolbox.
closes #248

Adds mongodb-tools to image

---

images/php-fpm/7.2.Dockerfile
images/php-fpm/7.3.Dockerfile
images/php-fpm/7.4.Dockerfile
images/php-fpm/8.0.Dockerfile
images/php-fpm/blackfire.ini
images/php-fpm/entrypoints/80-php-blackfire.sh

According to blackfire this is the current best way

Install Blackfire Agent and Probe within php containers

---

images/toolbox/Dockerfile

Added dns tools (ie: dig, host) and ssh client to the toolbox image

Added dns tools and ssh client to toolbox image

---

images/commons/Dockerfile
images/mariadb/10.6.Dockerfile
images/nginx/Dockerfile
images/node-builder/14.Dockerfile
images/node/14.Dockerfile
images/node/16.Dockerfile
images/node/18.Dockerfile
images/php-cli/7.4.Dockerfile
images/php-cli/8.0.Dockerfile
images/php-cli/8.1.Dockerfile
images/php-fpm/7.4.Dockerfile
images/php-fpm/8.0.Dockerfile
images/php-fpm/8.1.Dockerfile
images/postgres/11.Dockerfile
images/postgres/12.Dockerfile
images/postgres/13.Dockerfile
images/postgres/14.Dockerfile
images/python/3.10.Dockerfile
images/python/3.7.Dockerfile
images/python/3.8.Dockerfile
images/python/3.9.Dockerfile
images/redis/5.Dockerfile
images/redis/6.Dockerfile

only OpenResty missing a 3.16 bump

update upstream images for Alpine 3.16

---

helpers/TESTING_dockercompose.md
helpers/docker-compose.yml

Add tests for Node and Python by starting built-in webservers

add more helper tests

---

images/php-fpm/7.4.Dockerfile
images/php-fpm/8.0.Dockerfile
images/php-fpm/8.1.Dockerfile

Reverts uselagoon/lagoon-images#555

Revert "Update dependency newrelic/newrelic-php-agent to v9.21.0.311 (main)"

---

images/node-builder/14.Dockerfile
images/node-builder/16.Dockerfile
images/node-builder/18.Dockerfile

Fix for error at https://github.com/sgerrand/alpine-pkg-glibc/issues/185 and version bump to recent glibc

fix glibc build errors

---

images/commons/Dockerfile
images/mariadb/10.4.Dockerfile
images/mariadb/10.5.Dockerfile
images/mariadb/10.6.Dockerfile
images/nginx/Dockerfile
images/node-builder/14.Dockerfile
images/node-builder/16.Dockerfile
images/node-builder/18.Dockerfile
images/php-cli/7.4.Dockerfile
images/php-cli/8.0.Dockerfile
images/php-cli/8.1.Dockerfile
images/php-fpm/7.4.Dockerfile
images/php-fpm/8.0.Dockerfile
images/php-fpm/8.1.Dockerfile
images/python/3.10.Dockerfile
images/python/3.7.Dockerfile
images/python/3.8.Dockerfile
images/python/3.9.Dockerfile
images/ruby/3.0.Dockerfile
images/ruby/3.1.Dockerfile
images/solr/7.Dockerfile
images/solr/8.Dockerfile
images/varnish/6.Dockerfile

This Pull-request closes #374  by alphabetising the various lists of packages in apt-get/apk add/del/remove commands.
This practice is recommended by Docker here: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#sort-multi-line-arguments and makes it easier to visually scan a Dockerfile.
I did a full build of the images via `make build` after making the changes, and everything seems to work.

Alphabetise and format apk/apt-get add/del/install commands

---

Makefile
images/opensearch/2.Dockerfile
images/opensearch/Dockerfile
images/opensearch/docker-entrypoint.sh
images/opensearch/es-curl

Images have been created for Opensearch.
These are very close to the elasticsearch images, but because of naming conventions (and deprecated settings) they are being deliberately namespaced separately.

Add Opensearch 2 images

---

Makefile
helpers/TESTING_dockercompose.md
helpers/docker-compose.yml
images/python/3.11.Dockerfile

we managed to miss the python 3.11 release in October!

add python 3.11 image

---

Makefile
helpers/TESTING_dockercompose.md
helpers/docker-compose.yml
images/ruby/3.2.Dockerfile

Ruby 3.2 was released https://www.tiktok.com/@dappestcontrol/video/7185507456812993793
This PR adds the images and tests

Add Ruby3.2 image and tests

---

Makefile
helpers/TESTING_dockercompose.md
helpers/docker-compose.yml
images/redis-persistent/7.Dockerfile
images/redis/7.Dockerfile

Redis 7 was released a long time ago :facepalm: - this PR adds support for it to Lagoon images
https://redis.com/blog/redis-7-generally-available/

Add Redis7 images

---

images/php-fpm/8.0.Dockerfile
images/php-fpm/8.1.Dockerfile
images/php-fpm/8.2.Dockerfile

Reverts uselagoon/lagoon-images#684

Revert "Update dependency newrelic/newrelic-php-agent to v10.6.0.318 (main)"

---

images/php-fpm/8.0.Dockerfile
images/php-fpm/8.1.Dockerfile
images/php-fpm/8.2.Dockerfile

This PR adds the php tidy extension and relevant libraries.
Closes #792

add php tidy extension

---

images/nginx-drupal/drupal.conf

Port the latest changes from Drupals htaccess blocks to Nginx rules

---

helpers/TESTING_service_images_dockercompose.md

The syntax for the internal-services-test changed slightly - this fixes up the tests that use it.

update internal-services-test URL syntax

---

helpers/TESTING_base_images_dockercompose.md
helpers/images-docker-compose.yml
images/php-fpm/8.3.Dockerfile

Reinstalls New Relic and Blackfire agents in php 8.3.
Closes #905.

Install New Relic and Blackfire agents in PHP 8.3 images

---

images/php-cli/8.2.Dockerfile
images/php-fpm/8.1.Dockerfile
images/php-fpm/8.2.Dockerfile
images/php-fpm/8.3.Dockerfile

This PR adds the exif extension and dependencies to the PHP-based images.
Closes https://github.com/uselagoon/lagoon-images/issues/939

feat: add exif extension to php images

---

Jenkinsfile
helpers/TESTING_base_images_dockercompose.md
helpers/TESTING_service_images_dockercompose.md

With updates to uselagoon/lagoon-examples in https://github.com/uselagoon/lagoon-examples/pull/383 to include the new @lando/leia parser, we have had to make some parser changes here to accommodate.

tests: update to @lando/leia parsing

---

images/redis/conf/redis.conf

Increase default Redis maxmemory to 400MB (from 100MB)

---

Makefile
helpers/TESTING_service_images_dockercompose.md
helpers/services-docker-compose.yml
images/postgres-drupal/17.Dockerfile
images/postgres/17.Dockerfile

Postgres 17 is released - https://www.postgresql.org/about/news/postgresql-17-released-2936/

build: add postgres-17 image

---

Makefile
helpers/TESTING_base_images_dockercompose.md
helpers/images-docker-compose.yml
images/python/3.13.Dockerfile

Python 3.13 has been released - https://docs.python.org/3/whatsnew/3.13.html

build: add python-3.13 image

---

Makefile
helpers/TESTING_service_images_dockercompose.md
helpers/services-docker-compose.yml
images/valkey/8.Dockerfile
images/valkey/conf/ephemeral.conf
images/valkey/conf/persistent.conf
images/valkey/conf/valkey.conf
images/valkey/docker-entrypoint

This PR brings Valkey support to lagoon images.
Valkey is a community-led successor to Redis - read more at https://www.linuxfoundation.org/press/linux-foundation-launches-open-source-valkey-community
It's intended to be backwards compatible, but any integration should always be tested prior to first use.

build: initial valkey-8 image build

---

helpers/TESTING_service_images_dockercompose.md

Adds test for PR #1350 
* Creates a compressible file
* Requests brotli as compression
* ...
* Profit (or, at least confirm and pass tests)

Adds test for brotli compression
