uselagoon/lagoon-images

- Makefile
This PR actually points the docker_publish_amazeeio makefile task to amazeeio dockerhub.  Once merged, tagged images will also be created in the correct namespace for legacy users.
> Removing the amazeeio image publishing guardrail

- images/php-fpm/7.2.Dockerfile
- images/php-fpm/7.3.Dockerfile
- images/php-fpm/7.4.Dockerfile
This is what was in the [Lagoon repo](https://github.com/amazeeio/lagoon/blob/v1.9.1/images/php/fpm/Dockerfile#L9).
Fixes #32.
> Bump healthz-php to 0.0.6 (latest).

- images/php-fpm/7.2.Dockerfile
- images/php-fpm/7.3.Dockerfile
- images/php-fpm/7.4.Dockerfile
As per #40 - there a few changes in xdebug3 that should go through thorough testing prior to release.  This PR pins the xdebug version to the last known good one - 2.9.8 - whilst we test
> pin xdebug to 2.9.8 to avoid Xdebug3 b/c issues

- images/solr-drupal/solr7.7/conf/solrconfig.xml
The error in https://github.com/amazeeio/lagoon/issues/2261 was identified with a dual entry in the solrconfig that we provide.  This PR removes that dual entry to stop the error.
closes https://github.com/amazeeio/lagoon/issues/2261 and supersedes https://github.com/amazeeio/lagoon/pull/2262
> remove duplicate dataDir entry from 7.7 solrconfig

- images/php-fpm/entrypoints/50-ssmtp.sh
This PR updates the mail configuration for the `php-fpm` container to ensure it always falls back to sensible defaults if running on Lagoon. Older, legacy ssmtp options have also been removed.
> Updated ssmtp settings with sensible defaults

- images/nginx-drupal/drupal.conf
This PR adds logic to the `nginx-drupal` image to automatiaclly block `.sql.gz` files by default.
Closes #74
> Add .sql.gz to default block list for nginx-drupal

- images/php-cli/ssh_config
alternate resolution to #78 
The  /home/.ssh/lagoon_cli.key is only accessible to root users (e.g. https://github.com/uselagoon/lagoon-images/blob/main/images/php-cli/7.4.Dockerfile#L72) 
The version of openssh in use in Alpine 3.12 now errors for identityfiles in ssh_config, irregardless of whether they're needed or not - so non-root users get malformed key returns under certain circumstances.
This PR means that the lagoon_cli.key is only considered when a ssh command is run by a root localuser, removing the error message.
> add /home/.ssh/lagoon_cli.key for root localuser only

- renovate.json
ELK stack from 7.11 onwards is not available as APL, so should not be suggested as upgrade options from current APL-licensed versions https://www.elastic.co/pricing/faq/licensing
> Exclude ELK updates from 7.11 onwards

- images/php-cli/7.2.Dockerfile
- images/php-cli/7.3.Dockerfile
- images/php-cli/7.4.Dockerfile
- images/php-cli/8.0.Dockerfile
This PR adds the `mongodb-tools` package to the php-cli container, which enables the backup and restoration of mongodb from within this container.
> Adding mongodb-tools package to php-cli

- images/commons/Dockerfile
- images/commons/lagoon/entrypoints/90-cronjobs.sh
* Use a fork while we wait for the patch to land upstream.
* The command line has changed since the last version, so update to maintain the same logic.
> Allow crond to use a non-root working directory

- images/nginx/Dockerfile
- images/nginx/matomo/80-nginx-matomo-config
- images/nginx/matomo/README.md
Adds an entrypoint script to the base `nginx` image which will generate new NGINX configuration file that injects Matomo tracking snippets. There's 2 different options - a standard installation which requires a Matomo URL `MATOMO_URL` and Site ID `MATOMO_SITE_ID` the other option is providing a URL `MATOMO_TAG_MANAGER_URL` to a Tag manager script that will allow the use of Matomo Tag manager.
If no variables are set no config files are created and there's no affect to the current default behaviours.
closes #95
> Added support for injecting Matomo snippets via ngx_http_sub_module.

- helpers/update-versions.yml
- images/php-cli-drupal/7.3.Dockerfile
- images/php-cli-drupal/7.4.Dockerfile
- images/php-cli-drupal/8.0.Dockerfile
a new version of Drush launcher has been released which resolves issue like below
https://github.com/drush-ops/drush-launcher/issues/91
This pr updates the Drush launcher version to `0.9.1`
> Updated Drush launcher version to 0.9.1.

- images/nginx/docker-entrypoint
This PR updates the `nginx` image to use SHA-512 instead of Crypt to store basic auth hashes. This enables Nginx to correctly utilize more than the first eight characters of a supplied basic auth password.
Closes #140
> Update Nginx to use SHA-512 to store basic auth password hashes

- images/php-fpm/7.2.Dockerfile
- images/php-fpm/7.3.Dockerfile
- images/php-fpm/7.4.Dockerfile
- images/php-fpm/8.0.Dockerfile
This PR closes #127 
Essentially, if New Relic logs in the `cli` the results will be pushed to STDOUT.
This is a problem if you rely on the output of a PHP based tool (expecting it to, say, output JSON for further processing) - with the output redirected to STDERR, the user at least has the option of redirecting the STDERR output somewhere else, while still being able to process the output from the app  - this is particularly important for the New Relic warnings, since they're (1) not fatal, and (2) are likely not to have much affect on what's being accomplished with the cli tool being used.
> Changes output stream target for New Relic logs

- images/toolbox/Dockerfile
This PR adds both the `redis-cli` and `psql` binaries to the toolbox images, allowing us to connect to these resources using this same image as well.
> Adding redis-cli and psql to Toolbox image

- Makefile
- images/python/3.9.Dockerfile
This PR adds support for Python 3.9.
It also removes the pin on virtualenv 16.
> add Python 3.9 base images

- Makefile
- images/mariadb-drupal/10.4.Dockerfile
- images/mariadb-drupal/10.5.Dockerfile
- images/mariadb/10.4.Dockerfile
- images/mariadb/10.5.Dockerfile
- images/toolbox/Dockerfile
This PR adds version numbers to the mariadb images.
Given they release a minor version annually (https://mariadb.com/kb/en/mariadb-server/), it makes sense to pin there.
The current release `uselagoon/mariadb` is equivalent to `uselagoon/mariadb-10.4`
> version mariadb images

- Makefile
Instead of calling them "newly" versioned, refer to the section as "default" versioned - to allow us to change it later on
> use better terminology for default images

- images/php-cli/7.2.Dockerfile
- images/php-cli/7.3.Dockerfile
- images/php-cli/7.4.Dockerfile
- images/php-cli/Dockerfile
This change ensures the image build fails when the downloaded composer does not match the SHA256 hash.
The current syntax does not actually check whether the hash is correct and always passes, even if the hash does not match. It can be proven by changing a digit in the `COMPOSER_HASH_SHA256` variable and building the image.
> Fail image build if composer checksum does not match.

- images/php-fpm/entrypoints/71-php-newrelic.sh
before you could have set `NEWRELIC_ENABLED=false` and it was still started
> only accept `true` for $NEWRELIC_ENABLED

- images/varnish/6.Dockerfile
currently varnish-dev 6.5.2 is being pulled, leading to a version mismatch for the vmods
> ensure correct varnish-dev version is pulled for varnish 6

- Jenkinsfile
- Makefile
This PR adds a Makefile command to search through the repo for all upstream dockerfiles, and then perform a `docker pull` on these images to ensure that the images are being built using the latest images.
This will automatically occur in Jenkins, but can be run manually locally.
> add docker_pull command to Makefile to pull fresh upstream images

- images/commons/Dockerfile
- images/mariadb/10.5.Dockerfile
- images/node/12.Dockerfile
- images/node/14.Dockerfile
- images/node/16.Dockerfile
- images/php-cli/7.3.Dockerfile
- images/php-cli/7.4.Dockerfile
- images/php-cli/8.0.Dockerfile
- images/php-fpm/7.3.Dockerfile
- images/php-fpm/7.4.Dockerfile
- images/php-fpm/8.0.Dockerfile
- images/python/3.7.Dockerfile
- images/python/3.8.Dockerfile
- images/python/3.9.Dockerfile
- images/redis/5.Dockerfile
- images/redis/6.Dockerfile
This upgrade upgrades the upstream alpine images to the latest 3.14 release.
Effective this PR the following versions are in use:
3.14.2 All alpine-based images except:
3.14.1 nginx based images
3.9.4 solr-7.7 based images
3.8.5 mongodb image
3.7.3 varnish-5 based images
In addition, the following images are Debian-based:
11.0 solr-7
10.9 varnish-6 based images
> update to alpine 3.14

- renovate.json
This PR adds the PECL packages consumed by the PHP images to the renovate.json
This allows Renovate to suggest updates to packages as they are released onto PECL.
It does this by scanning the package source github repos for releases, but has been instructed to ignore major version bumps (i.e. Redis 4>5 and Xdebug 3>4)
> Add in PECL packages to renovate.json

- Makefile
- images/varnish-drupal/6.Dockerfile
- images/varnish/6.Dockerfile
Upstream varnish has [recently](https://github.com/varnish/docker-varnish/commit/9bbe2f325934f00ee5506c956e4883f3a8e6884e) moved to running varnish as an unprivileged user
To make this work, I have had to wrap the install, copy and fix-permission commands in a `USER root`, resetting it back to `USER varnish` afterwards
> change to "varnish" user as per upstream for varnish-6

- images/elasticsearch/6.Dockerfile
- images/elasticsearch/7.Dockerfile
- images/logstash/6.Dockerfile
- images/logstash/7.Dockerfile
- images/solr/7.7.Dockerfile
- images/solr/7.Dockerfile
- images/solr/8.Dockerfile
This PR adds new `SOLR_OPTS` for our Solr images, new `ES_JAVA_OPTS` for our ElasticSearch images, and new `LS_JAVA_OPTS` for our Logstash images to patch the CVE-2021-44228 vulnerability announced earlier today. 
More information on this vulnerability can be found here: https://github.com/advisories/GHSA-jfh8-c2jp-5v3q
Closes #357
> Adding SOLR_OPTS, LS_JAVA_OPTS, and ES_JAVA_OPTS to patch against CVE-2021-44228

- images/elasticsearch/6.Dockerfile
- images/elasticsearch/7.Dockerfile
- images/logstash/6.Dockerfile
- images/logstash/7.Dockerfile
- images/solr/7.7.Dockerfile
- images/solr/7.Dockerfile
- images/solr/8.Dockerfile
This PR actions the advice from the log4j team on how to best mitigate against CVE-2021-45046, namely removing the JndiLookup class from the classpath for all affected images
https://logging.apache.org/log4j/2.x/security.html
I've left the XX_OPTS in for the time being, but they can probably be removed
> remove the JndiLookup class from the classpaths for CVE-2021-45046 and CVE-2021-44228

- Jenkinsfile
The upstream lagoon-examples project has been reorganized slightly, and this PR modifies the Jenkinsfile here to accommodate these changes - https://github.com/uselagoon/lagoon-examples/pull/215
> fixup jenkinsfile tests for upstream lagoon-example repo changes

- helpers/update-versions.yml
- images/php-cli-drupal/7.4.Dockerfile
- images/php-cli-drupal/8.0.Dockerfile
- images/php-cli-drupal/8.1.Dockerfile
- images/php-cli/7.4.Dockerfile
- images/php-fpm/7.4.Dockerfile
- images/php-fpm/8.0.Dockerfile
- images/php-fpm/8.1.Dockerfile
This PR updates the following packages:
* NewRelic PHP Agent to 9.18.1.303
* Blackfire Agent to 2.5.2
* Composer 1.x to 1.10.24
* Drush 8.x to 8.4.10
* Drush Launcher to 0.9.3
closes #375
> update PHP agents and apps

- images/nginx/Dockerfile
As per https://github.com/openresty/docker-openresty there is now an alpine-apk image for openresty, built from the upstream package instead of built from source.
> use official openresty package image instead of source image

- Jenkinsfile
- Makefile
- helpers/TESTING_dockercompose.md
- helpers/docker-compose.yml
- images/commons/Dockerfile
- images/mariadb-drupal/10.6.Dockerfile
- images/mariadb/10.6.Dockerfile
- images/node/12.Dockerfile
- images/node/14.Dockerfile
- images/node/16.Dockerfile
- images/php-fpm/7.4.Dockerfile
- images/php-fpm/8.0.Dockerfile
- images/php-fpm/8.1.Dockerfile
- images/postgres-drupal/12.Dockerfile
- images/postgres-drupal/13.Dockerfile
- images/postgres-drupal/14.Dockerfile
- images/postgres/11.Dockerfile
- images/postgres/12.Dockerfile
- images/postgres/13.Dockerfile
- images/postgres/14.Dockerfile
- images/python/3.10.Dockerfile
- images/python/3.7.Dockerfile
- images/python/3.8.Dockerfile
- images/python/3.9.Dockerfile
- images/redis/5.Dockerfile
- images/redis/6.Dockerfile
Quite a bit here - firstly, all images are updated to alpine 3.15 (https://alpinelinux.org/posts/Alpine-3.15.0-released.html)
Secondly, we've added the following images:
* Python 3.10
* Postgres 13 and Postgres 14 (and -drupal variants)
* MariaDB 10.6 (and -drupal variant)
* Solr 8 has been moved from an "Experimental" to a published image
Thirdly, we've added additional testing for the above images
> update existing images to alpine 3.15

- images/mariadb/my.cnf
This allows a configurable wait_timeout value which retains the default `28800` value if not defined
> Add support for configurable wait_timeout

- images/php-fpm/7.4.Dockerfile
- images/php-fpm/8.0.Dockerfile
- images/php-fpm/8.1.Dockerfile
Experimental image build update to reduce weight of base images.
Result from running `make build/php-8.0-fpm` on this branch:
```
$ docker image ls lagoon/php-8.0-fpm
REPOSITORY           TAG       IMAGE ID       CREATED              SIZE
lagoon/php-8.0-fpm   latest    fbdce423c96c   About a minute ago   268MB
```
Versus current released image:
```
$ docker image ls uselagoon/php-8.0-fpm
REPOSITORY              TAG       IMAGE ID       CREATED       SIZE
uselagoon/php-8.0-fpm   latest    7f83e8db81b4   4 weeks ago   625MB
```
> Lightweight images

- images/nginx/Dockerfile
Whilst the upstream openresty project is dealing with Alpine packaging issues (https://github.com/openresty/openresty-packaging/issues/80) , we can pin the patch version to ensure we get the correct updates when they come out
> Pin to versioned OpenResty package image

- Makefile
- helpers/update-versions.yml
- images/php-cli-drupal/7.4.Dockerfile
- images/php-cli-drupal/8.0.Dockerfile
- images/php-cli-drupal/8.1.Dockerfile
- images/php-cli/7.4.Dockerfile
- images/php-fpm/7.4.Dockerfile
- images/php-fpm/8.0.Dockerfile
- images/php-fpm/8.1.Dockerfile
This Updates:
* New Relic PHP Agent to [9.20.0](https://github.com/newrelic/newrelic-php-agent/releases/tag/v9.20.0.310)
* Blackfire Agent to [2.7.0](https://github.com/blackfireio/docker/releases/tag/2.7.0)
* Composer 1 to [1.10.25](https://github.com/composer/composer/releases/tag/1.10.25)
* Drush Launcher to [0.10.1](https://github.com/drush-ops/drush-launcher/releases/tag/0.10.1)
These changes bring more PHP8.1 compatibility (New Relic, Blackfire and Drush Launcher.
It also corrects a couple of issues with the scan-images process
> update helper tools

- images/commons/fix-permissions
I noticed that `fix-permissions` was traversing the file system twice to set the file mode bits on directories. We can set all file mode bits for both directories and files at the same time. 
We could select file mode letter capital X - see `chmod` man page 
> (X) : execute (or search for directories) only if the file is a directory or already has execute permission for some user
This doesn't change build speed by much but I thought I'd share it anyway. It simplifies the permissions change using a common, long supported method.
> Invoke chmod once per directory to fix permissions

- images/php-fpm/7.4.Dockerfile
- images/php-fpm/8.0.Dockerfile
- images/php-fpm/8.1.Dockerfile
- images/php-fpm/php-fpm.d/global.conf
- images/php-fpm/php-fpm.d/www.conf
This avoids exiting immediately and returning an error for in-flight web
requests.
Closes: #444 
See this repo for a way to test this locally: https://github.com/smlx/test-php-fpm-graceful-exit
> feat: give php-fpm workers 30s to gracefully exit

- images/redis/conf/redis.conf
This PR implements the ability to configure redis' `maxmemory-policy` setting via the new `MAXMEMORYPOLICY` variable.
Partially fulfills #476
> Implementing MAXMEMORYPOLICY for redis images

- Makefile
The current makefile doesn't include the routines needed to build Postgres images for Drupal for any versions >11
> build postgres drupal images

- renovate.json
This PR expands the scope of the packages and extensions that can be under Renovate management:
This also covers:
* Composer v1 and v2
* Drush 8
* Drupal Console
* Drush Launcher
* New Relic PHP agent
* Blackfire.io agent
A separate PR will be submitted to make the dockerfiles compatible with these versions
> Add more PHP pacakges and extensions to renovate management

- images/php-fpm/7.4.Dockerfile
- images/php-fpm/8.0.Dockerfile
- images/php-fpm/8.1.Dockerfile
A new install process will need to be found whilst we work this out - https://github.com/newrelic/newrelic-php-agent/pull/403
> Revert "Update dependency newrelic/newrelic-php-agent to v9.21.0.311"

- images/nginx-drupal/drupal.conf
Allows access to security.txt (file on disk or provided via the securitytxt module) on the RFC8615 standard path.
> Added security.txt support.

- images/nginx/nginx.conf
Updated the configuration so JSON:API standard also uses gzip compression.
> Update nginx.conf to allow JSON:API standard

- images/commons/Dockerfile
- images/node-builder/14.Dockerfile
- images/node-builder/16.Dockerfile
- images/node-builder/18.Dockerfile
- images/node/14.Dockerfile
- images/node/16.Dockerfile
- images/node/18.Dockerfile
in #562 I bumped the glibc version and set a flag to handle a package clash. This unintentionally broke some builds.
To remedy the confluence of issues here,
* We no longer upgrade the apk packages in the nodejs base images we inherit (this is a bad idea anyway, as they have not been tested upstream)
* glibc 2.35 came with more serious configuration implications, that in conjunction with the inadvertent upgrade may render a build non-working.
Going forwards, we wll look to deprecate the use of sgerrand/alpine-pkg-glibc in favor of the alpine-native gcompat package, but this release is just intended to revert to the previous functionality.
> pin glibc to 2.34 and stop upgrading apk packages

- images/varnish/6.Dockerfile
The varnish user does not have access to the root group, so the docker-entrypoint cannot envplate the vcl files on startup locally. In Lagoon, the `10000` user is a member of the root group, so this works ok.
This PR just adds the root group to the varnish user for use locally.
> add varnish-6 user to root group for localdev

- helpers/TESTING_dockercompose.md
- images/rabbitmq/Dockerfile
- images/rabbitmq/cluster-rabbit.sh
As per https://www.rabbitmq.com/versions.html, RabbitMQ 3.8 is now EOL. Over the next couple of monthly releases, we will update the image to 3.11
> update to rabbit 3.9.24

- images/node-builder/14.Dockerfile
- images/node-builder/16.Dockerfile
- images/node-builder/18.Dockerfile
Recent releases of sgerrand's glibc musl<>glibc compatibility binary aren't installing cleanly in more recent versions of Alpine - as first identified in #571.
This PR replaces that binary with the native alpine gcompat package. This will require more testing prior to rollout.
> replace sgerrand/glibc with gcompat

- images/nginx-drupal/drupal.conf
Penetration testing revealed the possibility of information disclosure on the web.config file.
A threat actor performing reconnaissance on the application would look for any known vulnerabilities against an application via its reported software type and version. As things become outdated and vulnerable, an attacker will seek to exploit these vulnerabilities if they are aware of the software versions in use.
> Update standard nginx-drupal config to prevent possible information disclosure vulnerability

- helpers/TESTING_dockercompose.md
- images/rabbitmq/Dockerfile
3.10.7 is a matching release to 3.9.22 (i.e. before the Erlang issue that broke arm64 compatibility)
> update rabbitmq to 3.10.7

- images/commons/docker-sleep
The previous sleep loop was not interruptible, so termination of CLI pods usually took 30 seconds, which is the default Kubernetes grace period[0].
With this change such pods will terminate immediately upon receipt of SIGTERM.
[0] https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination
> fix: exit immediately on receipt of SIGTERM

- images/varnish/7.Dockerfile
Currently there is no arm v8/64 comaptible varnish 7.2 image
https://hub.docker.com/_/varnish/tags?page=1&name=7.2
> rollback varnish-7 to 7.1 for arm64 compatibility

- images/nginx-drupal/drupal.conf
Also return HTTP 404 (this is what the comment indicated should be returned, and I agree).
Fixes #636
> Prevent access to composer.json and composer.lock no matter the sub folder

- .gitignore
- Jenkinsfile
- helpers/.env
- helpers/TESTING_dockercompose.md
- helpers/docker-compose.yml
This PR adds an additional service into the helpers tests that allows for easy testing of read/write to various lagoon services
> add internal-services-test to helpers tests

- images/rabbitmq/Dockerfile
Reverts uselagoon/lagoon-images#623
This builds natively on ARM64, just not via QEMU. Reverting to test and investigate
> Revert "Update rabbitmq Docker tag to v3.10.13 (main)"

- images/nginx-drupal/drupal.conf
in #500, support for the drupal security.txt module was added to nginx-drupal. In practice though, a higher level match procluded access to .txt files outside of the sites/*/files folder.
This PR moves the security.txt block ahead of that block to ensure it processes ahead of it, and additionally removes the restriction on the .well-known folder being in the webroot - which enables the UI file download for signing in multilingual sites.
> move security.txt block in nginx-drupal

- images/php-fpm/8.2.Dockerfile
Support for php 8.2 was added in the new relic php agent 10.7 https://docs.newrelic.com/docs/release-notes/agent-release-notes/php-release-notes/php-agent-10-7-0-319/
> NewRelic now supported in php 8.2

- images/php-fpm/8.0.Dockerfile
- images/php-fpm/8.1.Dockerfile
- images/php-fpm/8.2.Dockerfile
Adds a new environment variable `NEWRELIC_DISTRIBUTED_TRACING_ENABLED` to allow disabling NewRelic distributed tracing.
closes #497
> Use environment variable to disable NewRelic distributed tracing

- Makefile
- helpers/TESTING_dockercompose.md
- helpers/docker-compose.yml
- images/node-builder/20.Dockerfile
- images/node-cli/20.Dockerfile
- images/node/20.Dockerfile
node-14 image also officially deprecates this month, but we won't remove it until next month
closes #732
> add node-20 images

- images/mariadb/10.11.Dockerfile
- images/node/16.Dockerfile
- images/node/18.Dockerfile
- images/node/20.Dockerfile
This adds the NodeJs updates to 3.18 now that they are available.
> Additional 3.18 updates to NodeJS

- images/commons/Dockerfile
- images/commons/fix-dir-permissions
- images/opensearch/2.Dockerfile
- images/opensearch/docker-entrypoint.sh
The current opensearch-2 image is unnecessarily large - this PR uses a new `fix-dir-permissions` command in commons to allow only directories to be permission fixed, reducing the layer size for impacted directories.
In addition, there are a couple of tweaks to the opensearch-2 image to optimise caching - removing the sole dependency on hostname to allow the removal of yum.
> Fix directory permissions to create smaller opensearch-2 image

- images/php-fpm/entrypoints/70-php-config.sh
This PR uses ep to add the variables/defaults in the 00-lagoon-php.ini file on the entrypoint instead of mv'ing then ep'ing. 
This means it can be run and rerun without error.
closes #783
> use ep to create 00-lagoon-php.ini

- images/mariadb/10.11.Dockerfile
- images/mariadb/10.4.Dockerfile
- images/mariadb/10.5.Dockerfile
- images/mariadb/10.6.Dockerfile
- images/node-cli/16.Dockerfile
- images/node-cli/18.Dockerfile
- images/node-cli/20.Dockerfile
- images/php-cli/8.0.Dockerfile
- images/php-cli/8.1.Dockerfile
- images/php-cli/8.2.Dockerfile
To support the new default authentication method in mysql8 `caching_sha2_password`, this adds a client library in case users need to communicate with mysql8 servers
> Add mariadb-connector-c package to support mysql8

- images/varnish/6.Dockerfile
We've been using Varnish 6.6 for the varnish-6 image. 6.6 was only ever a "fresh" release, and is no longer supported.
Varnish 6.0 is designated a LTS release and is still supported (and crucially, updated) - see https://varnish-cache.org/releases/
There should be no compatibility issues with this downgrade.
> use 6.0-lts version for Varnish-6

- images/php-fpm/8.0.Dockerfile
- images/php-fpm/8.1.Dockerfile
- images/php-fpm/8.2.Dockerfile
In the event that upstream PHP images aren't re-released with the curl 8.4.0 update to address CVE-2023-38545 and CVE-2023-38546, this PR introduces a dockerfile step to force upgrade the curl and libcurl versions.
Tracking docker image request at https://github.com/docker-library/php/issues/1449#issuecomment-1758800391
> force update php-based images curl to 8.4.0

- Jenkinsfile
- Makefile
With the examples updating to docker compose v2, having the images building using buildx was causing the docker compose to also use it for building the examples, resulting in errors.
This PR ensures that the images build in buildx and the examples build in docker
> use default builder for docker compose tests

- images/commons/Dockerfile
Using repackaged v1.0.3 envplate
and the
23.10.0-beta version of go-crond whilst we wait for https://github.com/webdevops/go-crond/issues/43
> update envplate and go-crond images

- images/php-fpm/8.0.Dockerfile
- images/php-fpm/8.1.Dockerfile
- images/php-fpm/8.2.Dockerfile
remove the block added in https://github.com/uselagoon/lagoon-images/pull/847 to pin the curl version after a security release
> remove block pinning curl version

- images/nginx/redirects-map.conf
The examples we provided weren't correct if someone were to use them exactly, without reading any NGINX docs, so I fixed those. While I was at it, I also expanded on the docs and made sure to point users to other resources.
> Improve comments and fix examples in redirects-map.conf

- Makefile
- helpers/TESTING_base_images_dockercompose.md
- helpers/images-docker-compose.yml
- images/php-cli-drupal/8.3.Dockerfile
- images/php-cli/8.3.Dockerfile
- images/php-fpm/8.0.Dockerfile
- images/php-fpm/8.1.Dockerfile
- images/php-fpm/8.2.Dockerfile
- images/php-fpm/8.3.Dockerfile
This is the first release of PHP8.3 images.
These images are released with a few caveats:
* The included version of nodejs for this image is now v20 - the next release of alpine (3.19) will have a v20 minimum.
* No Blackfire ([promised day 1](https://portal.productboard.com/platformsh/2-what-s-next-at-platform-sh/c/311-php-8-3-support-on-blackfire?utm_medium=social&utm_source=portal_share)) support
* New Relic support yet
* Removed Drupal Console and Drush Launcher and replaced with /app/vendor/bin in the path to pick up composer installed Drush
Note that there may be some issues with enabling Xdebug 3.3.0 (see https://www.drupal.org/project/drupal/issues/3405976)
> Add PHP8.3 images

- images/php-fpm/8.3.Dockerfile
This fix incorporates the remedy in https://github.com/Imagick/imagick/pull/641 to allow arm64 builds
Once the fix has been actioned upstream, the usual package can be called.
> fix for php8.3 imagick 3.7.0 build on arm64

- images/php-cli/8.1.Dockerfile
- images/php-cli/8.3.Dockerfile
- images/php-fpm/8.3.Dockerfile
There appears to be a segfault bug in recent php docker images. We're still investigating it - this PR reverts to Alpine 3.18 images for now, whilst we sort it out
> revert php 8.1 and 8.3 to alpine 3.18

- helpers/TESTING_service_images_dockercompose.md
- helpers/services-docker-compose.yml
- images/mariadb/10.11.Dockerfile
- images/mariadb/10.4.Dockerfile
- images/mariadb/10.5.Dockerfile
- images/mariadb/10.6.Dockerfile
- images/mariadb/entrypoints/100-mariadb-logging.bash
- images/mariadb/entrypoints/150-mariadb-performance.bash
Fixes:
- Our mariadb images include the `mysqltuner.pl` script but not all the perl packages required to run it
Adds:
- The ability to enable performance schema with `MARIADB_PERFORMANCE_SCHEMA` env var
- The ability to adjust slow query time (`MARIADB_LONG_QUERY_TIME`) and rate limit (`MARIADB_LOG_SLOW_RATE_LIMIT`)
> Improve MariaDB performance monitoring settings

- images/php-cli/8.3.Dockerfile
This PR moves the composer bin directories added for PHP9.3 in #877  to the end of the PATH variable, to ensure that any system-wide binaries are considered before any composer-installed ones
closes #934
> append composer bin dirs to path

- images/php-cli/8.1.Dockerfile
- images/php-cli/8.2.Dockerfile
- images/php-cli/8.3.Dockerfile
- images/php-fpm/8.1.Dockerfile
- images/php-fpm/8.2.Dockerfile
- images/php-fpm/8.3.Dockerfile
A change to the imagemagick packaging in alpine 3.19 (source https://gitlab.alpinelinux.org/alpine/aports/-/issues/13415)  seemingly caused an untraceable segfault in the PHP images.
Re-adding the missing imagemagick formats resolves the issue. Note that all previous formats have been re-added.
> Update php images to alpine3.19 and re-add missing ImageMagick codecs

- images/php-fpm/8.1.Dockerfile
- images/php-fpm/8.2.Dockerfile
- images/php-fpm/8.3.Dockerfile
Currenlty the PHP images since #629 have included the INTL module, but not all locales are included in the image and since alpine 3.16.0 only the US and english locales are included by default. This kind of negates the inclusion of intl.
Is it possible to include icu-data-full by default? This is a rather small increase of the image size but would make the images far more usefull ;)
> include icu-data-full

- images/nginx/fastcgi.conf
When looking to correctly surface true client IP with a number of reverse proxies in the mix we need access to the `X_FORWARDED_FOR` header in Drupal. With the default configuration this presents as a single IP address for the last hop in the chain:
``` text
$_SERVER['HTTP_X_FORWARDED_FOR']	127.0.0.1 (last hop)
```
With this change we explicitly set `X_FORWARDED_FOR` and other useful request identifiers back via fastcgi_params. This allows us to use `reverse_proxy_addresses` correctly in Drupal (and other applications analogs) to correctly act on the true client IP.
With this change PHP sees the following:
``` text
$_SERVER['HTTP_X_FORWARDED_FOR']	127.0.0.1 (last hop), 1.1.1.1 (remote_addr)
```
`$proxy_add_x_forwarded_for` appends the `remote_addr` to the IP list to allow us to access …
> Feat: Explicitly set fastcgi_params

- Makefile
- helpers/TESTING_base_images_dockercompose.md
- helpers/images-docker-compose.yml
- images/node-builder/22.Dockerfile
- images/node-cli/22.Dockerfile
- images/node/22.Dockerfile
Node.JS 22 was released 2024-04-24 and will be EOL in three years (2027-04-30)
https://github.com/nodejs/Release?tab=readme-ov-file#release-schedule
> build: add Node.JS v22 images and tests

- images/nginx/fastcgi.conf
This reverts a breaking change to `HTTP_X_FORWARDED_PROTO` introduced in commit fc919ba704325520bd993d60353f60eb3d9050b3.
Closes #987.
> Revert "Explicitly set fastcgi_params"

- images/commons/lagoon/entrypoints.bash
- images/commons/lagoon/entrypoints.sh
THis PR fixes the logic in the APPEND_NATIVE_ENTRYPOINT to make sure the variable is set before checking whether the file exists.
it also adds it to the entrypoints.bash for completeness
> fix: better APPEND_NATIVE_ENTRYPOINT logic

- images/node-cli/22.Dockerfile
- images/node-cli/ssh_config
- images/php-cli/ssh_config
Since Node 22 was just released and it's an LTS, hoping we can remove the hardcoded private key since it's only been a few days.
See #735.
> feat: deprecated lagoon_cli.key and remove from Node 22

- images/nginx-drupal/drupal.conf
Changes the regex block of `txt` and `md` files to allow the Drupal private filesystem path `/system/files`.
Closes #924.
> fix: don't block txt/md in Drupal private filesystem

- images/nginx/fastcgi.conf
Allow images that inherit from the base nginx image to include files that can extend the fastcgi param configuration. This will allow image consumers to add additional headers. Adding the include above the default params ensures that base configurations override any customisations that are made if required. This ensures that the base images can respond to to CVEs appropriately.
> Allow downstream to extend fastcgi params

- images/php-cli/8.1.Dockerfile
- images/php-cli/8.2.Dockerfile
- images/php-cli/8.3.Dockerfile
The [sleep script](https://github.com/uselagoon/lagoon-images/blob/main/images/commons/docker-sleep#L24) in the commons image checks for the `SIGTERM` signal, but the php-cli images specify `SIGQUIT` which causes unnecessary delay in termination. This PR sets the correct signal for php-cli images.
Tested locally with docker-compose. Before it would wait up to 20 seconds for the `cli` to terminate, after it is practically instant.
Closes #976.
> fix: use correct stop signal in php cli for faster termination

- Makefile
- helpers/TESTING_base_images_dockercompose.md
- helpers/images-docker-compose.yml
- images/ruby/3.3.Dockerfile
Ruby 3.0 hit EOL in late April, and 3.3 was available in December 2023
https://www.ruby-lang.org/en/downloads/branches/
> build: deprecate ruby3.0, introduce ruby3.3

- Makefile
- helpers/TESTING_service_images_dockercompose.md
- helpers/services-docker-compose.yml
- images/mysql/8.0.Dockerfile
- images/mysql/8.4.Dockerfile
- images/mysql/entrypoints/100-myql-logging.bash
- images/mysql/entrypoints/150-mysql-performance.bash
- images/mysql/entrypoints/200-mysql-envplate.bash
- images/mysql/entrypoints/9999-mysql-init.bash
- images/mysql/my.cnf
- images/mysql/mysql-backup.sh
- images/mysql/root/usr/share/container-scripts/mysql/readiness-probe.sh
This PR introduces new MySQL-8.0  and MySQL-8.4 base images.
Note that whilst it is functionally similar to the MariaDB image, there are a few differences:
* All variables are now namespaced MYSQL_* instead of MARIADB_*
* there is no mysql-X-drupal variant. This means that the default user, pass and database are all lagoon (instead of drupal) - modify the docker-compose or settings files accordingly
* You should assume there is no migration path between mysql and mariadb for local stored databases. Any migration should occur using export/import dumps
* These images now force mysql_native_password as that's still the managed DB way https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/MySQL.KnownIssuesAndLimitations.html
We intend to only release the LTS images - this means there will be …
> Add MySQL 8.0 and 8.4 images

- images/mariadb/10.11.Dockerfile
- images/mariadb/10.4.Dockerfile
- images/mariadb/10.5.Dockerfile
- images/mariadb/10.6.Dockerfile
MariaDB has introduced a breaking change in https://mariadb.org/mariadb-dump-file-compatibility-change/
This PR just pins the mariadb versions to "known good" ones until we work out how to handle this
> chore: temp pin mariadb versions

- images/nginx/Dockerfile
- images/nginx/basic_auth.conf
- images/nginx/helpers/020_basic-auth.conf
Closes #857 
This PR implements a `map` directive that sets a variable which decides whether basic authentication should be enabled or not, based on if the request is an OPTIONS request. If it is not, it will use whatever is set by the BASIC_AUTH environment variable, just like before.
This shouldn't be a breaking change :)
> Allow OPTIONS requests when using basic auth

- images/php-fpm/entrypoints/50-ssmtp.sh
The generated `ssmtp.conf` file from the entrypoint can now determine if `host.docker.internal` has a valid mailhog instance running.
```
php:/app$ cat /etc/ssmtp/ssmtp.conf
FromLineOverride=yes
mailhub=host.docker.internal:1025
php:/app$ nc -zv host.docker.internal 1025
host.docker.internal (192.168.65.254:1025) open
php:/app$ sendmail -v  test@test.com < /tmp/mail.txt
[<-] 220 mailhog.example ESMTP MailHog
[->] HELO 7ab411118f33
[<-] 250 Hello 7ab411118f33
[->] MAIL FROM:<user@7ab411118f33>
[<-] 250 Sender user@7ab411118f33 ok
[->] RCPT TO:<test@test.com>
[<-] 250 Recipient test@test.com ok
[->] DATA
[<-] 354 End data with <CR><LF>.<CR><LF>
[->] Received: by 7ab411118f33 (sSMTP sendmail emulation); Wed, 07 Aug 2024 02:46:20 +0000
[->] From: "user" <user@7ab411118f33>
[->] Date: Wed, 07 …
```
> Feat: Add support for host.docker.internal for SSMTP.

- images/commons/Dockerfile
- images/mongo/4.Dockerfile
- images/node-cli/18.Dockerfile
- images/node-cli/20.Dockerfile
- images/node-cli/22.Dockerfile
- images/node/18.Dockerfile
- images/node/20.Dockerfile
- images/node/22.Dockerfile
- images/php-cli/8.1.Dockerfile
- images/php-cli/8.2.Dockerfile
- images/php-cli/8.3.Dockerfile
- images/php-fpm/8.1.Dockerfile
- images/php-fpm/8.2.Dockerfile
- images/php-fpm/8.3.Dockerfile
- images/postgres/12.Dockerfile
- images/postgres/13.Dockerfile
- images/postgres/14.Dockerfile
- images/postgres/15.Dockerfile
- images/postgres/16.Dockerfile
- images/python/3.10.Dockerfile
- images/python/3.11.Dockerfile
- images/python/3.12.Dockerfile
- images/python/3.8.Dockerfile
- images/python/3.9.Dockerfile
- images/redis/6.Dockerfile
- images/redis/7.Dockerfile
- images/ruby/3.1.Dockerfile
- images/ruby/3.2.Dockerfile
- images/ruby/3.3.Dockerfile
This PR updates all images to the latest Alpine release - https://alpinelinux.org/posts/Alpine-3.20.0-released.html
However, the version of the mariadb-client in 3.20 introduced a [backwards incompatible update](https://mariadb.org/mariadb-dump-file-compatibility-change/) to the mariadbdump command. To mitigate this, I have pinned the mariadb-client package in the cli images to a version that is known to work with all versions of mariadb whilst we work out how best to implement the update.
> build: update images to alpine 3.20

- images/nginx/helpers/400_custom-404.conf
Having a custom 404 helper would be a convenient config file to have in the base image. I thought this might be helpful to others.
Nuxt and other static site generators render a custom 404 to /404.html by default. If the 404.html file is not found, Nginx still renders its standard boring openresty 404 so there seems to be no harm in having the default there and avoiding needing to copy it into the app's nginx dockerfile.
Thoughts?
> Adds a custom 404 handler, common for static rendered HTML sites

- images/mysql/8.0.Dockerfile
- images/mysql/8.4.Dockerfile
This PR uses the /sbin/tini provided by krallin/tini instead of the native oraclelinux tini to remain consistent with all the other images.
closes #1127
> Replace upstream tini with krallin/tini in MySQL image

- helpers/TESTING_service_images_dockercompose.md
- helpers/services-docker-compose.yml
- images/postgres-ckan/11.Dockerfile
- images/postgres-drupal/11.Dockerfile
- images/postgres/11.Dockerfile
PostgreSQL 11 has been out of support since November 2023
This final image adds the necessary LABELs to show it as deprecated to Lagoon, before it is removed next month.
> Deprecate Postgres 11 image

- images/varnish/6.Dockerfile
- images/varnish/varnish-start.bash
The upstream varnish image has moved from bullseye to bookworm, so this PR uses the correct packages.
> chore: update varnish-6 packages to bookworm

- helpers/TESTING_base_images_dockercompose.md
- images/php-fpm/8.1.Dockerfile
- images/php-fpm/8.2.Dockerfile
- images/php-fpm/8.3.Dockerfile
- renovate.json
We've been seeing build failures on arm architecture with the current pecl install process - this PR switches to using the commonly-used mlocati version - which also allows installing from source - which we need for PHP8.3 and 8.4 support in ImageMagick
> chore: use php-extension-installer for pecls

- images/mariadb/entrypoints/9999-mariadb-init.bash
- images/mysql/entrypoints/9999-mysql-init.bash
The readiness probe in the mysql image fails when calling `/usr/share/container-scripts/mysql/readiness-probe.sh` due to no local socket defined.
This sets the socket in the mysql image so that is available to the readiness probes.
Additionally, this adds another init file in both the mysql and mariadb images that doesn't contain the vendor name.
> fix: local socket in mysql images

- images/mongo/4.Dockerfile
- images/mysql/8.0.Dockerfile
- images/mysql/8.4.Dockerfile
- images/node-cli/18.Dockerfile
- images/node-cli/20.Dockerfile
- images/node-cli/22.Dockerfile
- images/node/18.Dockerfile
- images/node/20.Dockerfile
- images/node/22.Dockerfile
- images/php-cli/8.1.Dockerfile
- images/php-cli/8.2.Dockerfile
- images/php-cli/8.3.Dockerfile
- images/php-fpm/8.1.Dockerfile
- images/php-fpm/8.2.Dockerfile
- images/php-fpm/8.3.Dockerfile
- images/rabbitmq/Dockerfile
- images/redis/6.Dockerfile
- images/redis/7.Dockerfile
- images/solr/9.Dockerfile
- images/valkey/8.Dockerfile
In #891 we added rsync and tar to images - this PR goes further, adding them to more images, and moving them into the php/node web images instead of the cli images.
> build: add rsync & tar to missing images

- Makefile
- helpers/TESTING_base_images_dockercompose.md
- helpers/images-docker-compose.yml
- images/php-cli-drupal/8.4.Dockerfile
- images/php-cli/8.4.Dockerfile
- images/php-fpm/8.4.Dockerfile
This PR adds support for PHP and migrates the PHP extension installation to use mlocati/php-extension-installer
It also uses a fork of Imagick that has the necessary components for PHP8.3 and PHP8.4 support in-place. This is not intended as a long-term solution, but the workarounds are better managed in a local repo than in the Dockerfile.
> Add php8.4 support

- images/solr/8.Dockerfile
- images/solr/9.Dockerfile
To fix the package versions for rsync in the solr images - https://ubuntu.com/blog/rsync-remote-code-execution - we've introduced a minimum version fix
> build: fix minimum rsync versions for solr images

- helpers/TESTING_base_images_dockercompose.md
- helpers/TESTING_service_images_dockercompose.md
- images/php-cli/8.1.Dockerfile
- images/php-cli/8.2.Dockerfile
- images/php-cli/8.3.Dockerfile
- images/php-cli/8.4.Dockerfile
Small change to ensure node installs with full compatibility into the PHP images. May not be needed forever, but arises because the base image is behind the added package. We don't usually upgrade base packages unless something's broken.
Also tidied some old docker-compose references that slipped through
> chore: upgrade musl to fix node install in php images

- Jenkinsfile
- Makefile
This PR moves from the Scripted syntax to the declarative syntax, same as in uselagoon/lagoon
It also cleans up a bit of the logic around arm64 based pushes to try and minimize failure rates
> build: use declarative syntax for Jenkins

- images/opensearch/2.Dockerfile
The opensearch-alerting plugin can't be removed unless the opensearch-security-analytics plugin is removed first, which is also unneeded.
> chore: update opensearch removed plugins

- images/php-cli/8.1.Dockerfile
- images/php-cli/8.2.Dockerfile
- images/php-cli/8.3.Dockerfile
- images/php-cli/8.4.Dockerfile
- images/php-fpm/8.1.Dockerfile
- images/php-fpm/8.2.Dockerfile
- images/php-fpm/8.3.Dockerfile
- images/php-fpm/8.4.Dockerfile
In #1223 a musl upgrade was needed to install the latest node packages. This can cause an apk dependency mismatch, so moving it to base image ensures correct resolution.
> chore: move musl upgrade to php-fpm

- images/opensearch/2.Dockerfile
- images/php-cli/8.1.Dockerfile
- images/php-cli/8.2.Dockerfile
- images/php-cli/8.3.Dockerfile
- images/php-cli/8.4.Dockerfile
- images/php-fpm/8.1.Dockerfile
- images/php-fpm/8.2.Dockerfile
- images/php-fpm/8.3.Dockerfile
- images/php-fpm/8.4.Dockerfile
Once https://github.com/uselagoon/build-deploy-tool/pull/192 is released, all images that may have cronjobs need to have the flock binary to run them. In testing, only Opensearch-2 was missing it, hence the addition here, in case anyone wants cron!
> chore: add util-linux-core to provide flock for cron

- images/solr-drupal/9.Dockerfile
The `<lib/>` directives as used by Drupals search_api_solr are no longer supported: https://solr.apache.org/guide/solr/latest/upgrade-notes/major-changes-in-solr-9.html#solr-9-8 
Related d.o. issue https://www.drupal.org/project/search_api_solr/issues/3508084
---
I think adding the modules used by the jump-start config is fair. 
I think we should _not_ enable the `<lib/>` directives via workaround property since the directives will be gone in Solr 10 anyway.
> SOLR: Fix for solr 9.8 breaking changes in module handling

- images/mariadb/10.11.Dockerfile
- images/node-cli/18.Dockerfile
- images/node-cli/20.Dockerfile
- images/node-cli/22.Dockerfile
- images/php-cli-drupal/drush.yml
- images/php-cli/8.1.Dockerfile
- images/php-cli/8.2.Dockerfile
- images/php-cli/8.3.Dockerfile
- images/php-cli/8.4.Dockerfile
- images/php-cli/mariadb-client.cnf
In https://github.com/uselagoon/lagoon-images/pull/1031 we pinned the versions of mariadb-client in use in Lagoon Images, to avoid having to deal with the sandboxing introduced in https://mariadb.org/mariadb-dump-file-compatibility-change/
In this PR, we update the versions of mariadb-client used for all CLI images (as well as the 10.11 server image). One complication of this is that the mariadb-client in version 11.4 enables SSL mode on connections by default. As Lagoon uses only internal traffic for database connections locally and in the cloud, we do not have SSL configured. I have added the necessary configuration to the default drush and mariadb-dump commands to cover most scenarios.
This now means that any dump taken (via drush, wp-cli, mariadb-dump) in a cli pod will be taken in …
> update mariadb-client to the latest available version in alpine packages

- images/node-cli/18.Dockerfile
- images/node-cli/20.Dockerfile
- images/node-cli/22.Dockerfile
- images/php-cli/8.1.Dockerfile
- images/php-cli/8.2.Dockerfile
- images/php-cli/8.3.Dockerfile
- images/php-cli/8.4.Dockerfile
- images/php-cli/legacy-entrypoints/90-composer-path.sh
Fixes #1265 
Before this PR:
```
cli-drupal:/app$ env | grep -i path
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/app/vendor/bin:/home/.composer/vendor/bin:/app/vendor/bin
cli-drupal:/app$ bash -l
cli-drupal:/app$ env | grep -i path
PATH=/home/.composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```
With this PR:
```
cli-drupal:/app$ env | grep -i path
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/app/vendor/bin:/home/.composer/vendor/bin
cli-drupal:/app$ bash -l
cli-drupal:/app$ env | grep -i path
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/app/vendor/bin:/home/.composer/vendor/bin
```
I didn't spend a lot of time thinking how to keep the php 8.1/8.2 images backwards compatible. Happy to …
> fix: $PATH is different when starting subshells

- images/mariadb-drupal/10.4.Dockerfile
- images/mariadb-drupal/10.5.Dockerfile
- images/mariadb/10.4.Dockerfile
- images/mariadb/10.5.Dockerfile
This PR is the first step in deprecating the publication of MariaDB 10.4 and 10.5 images, which are both now built using very superseded Alpine images.
> chore: add deprecated label to MariaDB 10.4 and 10.5

- images/php-cli-drupal/drush.yml
Now that https://github.com/drush-ops/drush/pull/6249 has been added to drush, this adds the necessary options to all drush subcommands.
Closes #1273
> chore: add disable-ssl override to all drush commands

- Makefile
- helpers/TESTING_service_images_dockercompose.md
- helpers/services-docker-compose.yml
- images/commons/Dockerfile
- images/redis/8.Dockerfile
- images/redis/docker-entrypoint
Now that Redis is again published as AGPLv3 https://redis.io/blog/redis-8-ga/ we can re-add updated Redis images as well as Valkey-based ones.
Note that as per Valkey-based images, there is no seperate redis-8-persistent image, instead setting `REDIS_FLAVOR=persistent` as an env var will activate the persistent storage option
> build: initial redis-8 image

- Makefile
- helpers/TESTING_base_images_dockercompose.md
- helpers/images-docker-compose.yml
- images/node-builder/18.Dockerfile
- images/node-builder/24.Dockerfile
- images/node-cli/18.Dockerfile
- images/node-cli/24.Dockerfile
- images/node/18.Dockerfile
- images/node/24.Dockerfile
Now that Node 24 has been released, and Node 18 EOL, we should add the new images, and mark the old ones ready to deprecate, pending removal next release.
> add node-24 images, mark node-18 deprecated

- images/redis/8.Dockerfile
Now https://github.com/redis/docker-library-redis/issues/444 is resolved, we can add packages to the base image as before.
> chore: remove redis-8 apk workaround

- images/mysql/8.4.Dockerfile
Reverts uselagoon/lagoon-images#1375
There's currently no ARM image, so this needs to be reverted for now
> Revert "chore(deps): update mysql docker tag to v8.4.6 (main)"

- images/mariadb/10.11.Dockerfile
Alpine updated the version of the mariadb packages on 3.20 to 10.11.14
https://gitlab.alpinelinux.org/alpine/aports/-/commit/ae89d56a56b92c980eb20c5ec2d66e495064b9ed
> chore: update version of mariadb-server 10.11

- images/solr-drupal/8.Dockerfile
- images/solr/8.Dockerfile
Solr 8 has been EOL since October 2024, but the base images continued to be updated until April 2025
This PR sets the labels to flag it for removal next month
closes #1412
> build: deprecate solr-8 based images
